### PR TITLE
Small improvements to Diagnostics

### LINKED ISSUE #699: GCM runs : interactions between Diagnostics.jl and moisture models (undefined var \rhoq_tot)
Command to replicate this:

`julia --project experiments/GCM/heldsuarez.jl --diagnostics-interval=1` 

Stacktrace : https://gist.github.com/akshaysridhar/791064451d3c9bd008397a7e97cdafef

There is an issue with the way `MoistureModel`, `Diagnostics` interact (and presumably with other such variables defined in `AtmosModel` subcomponents). 

Here, if a `DryModel()` is the moisture model type, there is an issue with getting averages for the moisture variables - a `CLIMA.VariableTemplates.GetVarError` is triggered for the \rhoq_tot variable(e.g. \rhoq_tot which appears in `compute_horzsums!` and `gather_diagnostics`). With `DryModel()` active `state.moisture.\rhoq_tot` is not defined. Interaction with `EquilMoist()` is fine (since we define `state.moisture.\rhoq_tot`)

See also #702 

@slifer50 @kpamnany @bischtob

### LINKED ISSUE #702: Diagnostics implementation is Atmos-specific
Will fail if run with any other model.

### PR DESCRIPTION
**Pull request by kpamnany**
Slightly better structure now.

- Supports different balance laws (stubs for Ocean diagnostics added) (fixes #702)
- Temporary fix for use of non-EquilMoist models (fixes #699)

### CODE REVIEW

File: src/Diagnostics/AtmosDiagnostics.jl [hunk 1]
```diff
@@ -0,0 +1,340 @@
...
+function compute_thermo!(bl, state, aux, k, ijk, ev, e, thermoQ)
+    e_tot = state.ρe / state.ρ
+    ts = thermo_state(bl.moisture, bl.orientation, state, aux)
+    e_int = internal_energy(ts)
+    Phpart = PhasePartition(ts)
+
+    th = thermo_vars(thermoQ[ijk,e])
+    th.q_liq     = Phpart.liq
+    th.q_ice     = Phpart.ice
+    th.q_vap     = Phpart.tot-Phpart.liq-Phpart.ice
```
Comment (charleskawczynski) [inline src/Diagnostics/AtmosDiagnostics.jl]:
```suggestion
    th.q_vap     = vapor_specific_humidity(ts)
```
